swagger: "2.0"
info:
  title: Speeddate Spawnerservice
  description: HTTP service for managing game-instances
  version: ""
host: :8001
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /spawn:
    post:
      tags:
      - spawn
      summary: new spawn
      description: Spawn a new gameserver.
      operationId: spawn#new
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /swagger/swagger.json:
    get:
      summary: Download ../../gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
securityDefinitions:
  jwt:
    type: apiKey
    description: |-
      Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint. Supports scopes "api:read" and "api:write".
      **Security Scopes**:
        * `api:read`: Read-only access
        * `api:write`: Read and write access
    name: Authorization
    in: header
