apiVersion: v1
appVersion: "0.0.1"
description: A Helm chart for SpeedDate Masterserver
name: speeddate
version: 0.0.1
keywords:
  - go
  - golang
  - multiplayer
  - microservice
  - game-development