apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gameservers.speeddate.dev
  labels:
    component: crd
  annotations:
    "helm.sh/hook": "crd-install"
spec:
  group: speeddate.dev
  version: v1alpha1
  scope: Namespaced
  names:
    kind: GameServer
    plural: gameservers
    shortNames:
    - gs
    singular: gameserver
