apiVersion: v1
kind: Service
metadata:
  name: speeddateui
  namespace: {{ .Release.Namespace }}
  labels:
    app: speeddateui
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.speeddateui.Port }}
    name: http
  selector:
    app: speeddateui
