apiVersion: v1
kind: Service
metadata:
  name: storagesvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: storagesvc
spec:
  ports:
  - port: 8001
    targetPort: {{ .Values.storagesvcSettings.Port }}
    name: http
  selector:
    app: storagesvc
