apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-vs
spec:
  hosts:
  - {{ .Values.hosts.api }}
  gateways:
  - sd-gateway
  http:
  - match:
    - uri:
        prefix: /storage/
    route:
    - destination:
        host: storagesvc.default.svc.cluster.local
  - match:
    - uri:
        prefix: /auth/
    route:
    - destination:
        host: authsvc.default.svc.cluster.local
