apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sd-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  #DOC: Ports have to be opened by istio, https://github.com/istio/istio/issues/7242
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.host }}
  #TODO: test https https://istio.io/docs/tasks/traffic-management/secure-ingress/
  # - port:
  #     number: 443
  #     name: https
  #     protocol: HTTPS
  #   tls:
  #     mode: SIMPLE
  #     serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
  #     privateKey: /etc/istio/ingressgateway-certs/tls.key
  #   hosts:
  #   - "httpbin.example.com"
