apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ui-vs
spec:
  hosts:
  - {{ .Values.hosts.ui }}
  gateways:
  - sd-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: speeddateui
        port:
          number: 80
