swagger: "2.0"
info:
  title: Speeddate Userservice
  description: HTTP service for managing users in the SpeedDate-system
  version: ""
host: localhost:8001
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /auth/login:
    post:
      tags:
      - authorize
      summary: login authorize
      description: Creates a valid JWT
      operationId: authorize#login
      responses:
        "204":
          description: No Content response.
          headers:
            Access-token:
              description: Generated JWT
              type: string
      schemes:
      - http
      security:
      - basic: []
  /swagger/swagger.json:
    get:
      summary: Download ../../gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
securityDefinitions:
  basic:
    type: basic
    description: Basic authentication used to authenticate security principal during
      signin
