apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-vs
spec:
  hosts:
  - {{ .Values.hosts.api }}
  gateways:
  - sd-gateway
  http:
  - match:
    - uri:
        prefix: /user/
    route:
    - destination:
        host: usersvc
        port:
          number: 80
  - match:
    - uri:
        prefix: /auth/
    route:
    - destination:
        host: authsvc
        port:
          number: 80
---