apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: speeddateui-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: speeddateui
        version: v1
    spec:
      containers:
      - name: speeddateui
        image: {{.Values.image.imageRegistry}}/speeddateui:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}        
        ports:
        - containerPort: {{ .Values.speeddateui.Port }}
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
---