apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cockroachdb-external
spec:
  hosts:
  - {{ .Values.storagesvcSettings.DbHostname }}
  ports:
  - name: tcp
    number: {{ .Values.storagesvcSettings.DbPort }}
    protocol: tcp
  location: MESH_EXTERNAL
  resolution: STATIC  
  endpoints:
  - address: {{ .Values.storagesvcSettings.DbIP }}
    ports:
      tcp: {{ .Values.storagesvcSettings.DbPort }}
---